name: Build MacOS

on: 
  push:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'LICENSE'
        - '.gitignore'
        - 'README.md'
        - 'README_en.md'
        - 'resource/**'
        - 'translations/**'
        - 'docs/**'
  pull_request:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'LICENSE'
        - '.gitignore'
        - 'README.md'
        - 'README_en.md'
        - 'resource/**'
        - 'translations/**'
        - 'docs/**'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [6.2.4]
        qt_arch: [clang_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          install-deps: 'true'
          modules: 'qt5compat addons.qtnetworkauth addons.qtmultimedia addons.qtimageformats'
          cached: 'false'
      - name: cache vcpkg
        uses: actions/cache@v3
        with:
          path: C:\vcpkg\downloads
          key: ${{ runner.os }}-vcpkg-download-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-download-${{ matrix.os }}-
            ${{ runner.os }}-vcpkg-download-
      - uses: actions/cache@v3
        with:
          path: C:\vcpkg\installed
          key: ${{ runner.os }}-vcpkg-installed-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-installed-${{ matrix.os }}-
            ${{ runner.os }}-vcpkg-installed-
      - name: Install libraries with vcpkg
        run: |
          brew install nasm
          vcpkg install breakpad ffmpeg
      - name: fetch code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          qmake
          make
